CREATE TABLE CLIENTE (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME_COMPLETO VARCHAR(255) NOT NULL UNIQUE,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	SEXO ENUM('M', 'F') NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CIDADE_ID BIGINT,
	IS_ADMIN INT DEFAULT 0,
	SENHA VARCHAR(400) NOT NULL,
	
	FOREIGN KEY (CIDADE_ID) REFERENCES CIDADES(ID) ON DELETE SET NULL 
);